[[constraint]]
  branch = "master"
  name = "github.com/alexjlockwood/gcm"

[[constraint]]
  name = "github.com/gorilla/handlers"
  version = "1.3.0"

[[constraint]]
  name = "github.com/gorilla/mux"
  version = "1.6.2"

[[constraint]]
  name = "github.com/kyokomi/emoji"
  version = "1.5.1"

[[constraint]]
  name = "github.com/prometheus/client_golang"
  version = "0.8.0"

[[constraint]]
  branch = "master"
  name = "github.com/prometheus/common"

[[constraint]]
  name = "github.com/sideshow/apns2"
  version = "0.14.0"

[[constraint]]
  name = "github.com/tylerb/graceful"
  version = "1.2.15"

[[constraint]]
  name = "gopkg.in/throttled/throttled.v1"
  version = "1.0.0"

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/appleboy/go-fcm"
  version = "0.1.3"
